### PR TITLE
fix: make repo, user and branch url safe

### PR DESCRIPTION
**Pull request by bahrmichael**
This is a revival of https://github.com/BetaHuhn/deploy-to-vercel-action/pull/184

> 👋 hey, thanks for writing this great library!
>
> I encountered an issue if my repository contained a . character, for instance mysite.com. The output URL would be mysite.com-1234.vercel.app, which isn't a valid domain.
>
> I also encountered an issue if my branch contained a / character, for instance ci/pipeline. The output would be myrepo-ci/pipeline.vercel.app, which isn't a valid domain either.

This PR makes sure that the params repo, user and branch are url safe, due to problems explained in the original PR. I used https://perishablepress.com/stop-using-unsafe-characters-in-urls as a source of what's URL safe and what's not, and then added an inverted regex to only keep relevant characters.

### CODE REVIEW

**Comment by bahrmichael** [comment]
@BetaHuhn Could we get your eyes on this?

**Comment by bahrmichael** [comment]
This PR is not stale.

**Review by BetaHuhn — APPROVED** [review]
Thanks!

**Comment by bahrmichael** [comment]
Thank you :)

**Pull request merged**
