### PR TITLE
:arrow_up: Bump to node20

### PR DESCRIPTION
**Pull request by boredland**
Just added engines, switched to node 20 and rebuilt.

### CODE REVIEW

**Comment by mlahargou** [comment]
@BetaHuhn Any chance we could get this in the next release to get rid of the deprecation notice?

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: BetaHuhn/deploy-to-vercel-action@6 43bc80032ba62ca41d1a9aaba7b38b51c2b8646. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by fabn** [comment]
+1

**Comment by mountainash** [comment]
This was done in 8af10c0d27f52b66d8e32d934eb6f87056a065e0 of https://github.com/mountainash/fork-deploy-to-vercel-action/

**Review by BetaHuhn — APPROVED** [review]
Thanks @boredland!

**Pull request merged**
