### PR TITLE
Fix: added missing force param in action manifest

### LINKED ISSUE #192: `FORCE` option unrecognized
In the docs you have the `FORCE` option to skip vercels build cache. But when used throws the following warning:

Screen Shot 2022-07-02 at 15 45 26

### PR DESCRIPTION
**Pull request by Elindorath**
Should fix #192

### CODE REVIEW

**Comment by Elindorath** [comment]
Just preventing the bot to close this

**Comment by Elindorath** [comment]
Once again, just preventing the bot to close this. @BetaHuhn any thoughts on this?

**Comment by Elindorath** [comment]
Once again, just preventing the bot to close this. @BetaHuhn any thoughts on this?

**Review by BetaHuhn — APPROVED** [review]
Thanks! Sorry for the delay

**Pull request merged**
